name: jtreg-intellij-plugin.yml
on:
  release:
    types: [created]

jobs:
  jtreg-intellij-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: 'Build JTReg'
        shell: bash
        run: bash make/build.sh
      - name: 'Build IntelliJ Plugin'
        shell: bash
        run: cd plugins/idea && sh gradlew clean build
      - name: 'Upload IntelliJ Plugin'
        run: |
          gh release upload ${{ github.event.release.tag_name }} plugins/idea/build/distributions/jtreg-plugin-1.16.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

